server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: mns-trs-transport-in
          group: inConsumer
        input:
          destination: mns-trs-transport-out
          group: outConsumer


  rabbitmq:
    username: rabbitAdminUser
    password: rabbitAdminPwd