server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: mns-trs-transport-in
        input:
          destination: mns-trs-transport-out
      rabbit:
        bindings:
          output:
            producer:
              exchangeType: topic
              routingKeyExpression: '"#"'

  rabbitmq:
    username: guest
    password: guest
